repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.8
    hooks:
      # Run the formatter first.
      - id: ruff-format
      # Run the linter second.
      - id: ruff
        args: [ --fix ]
