[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_between_sections = 1
known_first_party = ["chem_utils"]
force_alphabetical_sort_within_sections = true