name: Flake8 Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.2.0
          
      - name: Create flake8 config
        run: |
          echo "[flake8]
          max-line-length = 127
          max-complexity = 10
          per-file-ignores =
              __init__.py: F401
          " > .flake8
          
      - name: Lint with flake8
        run: |
          # Run flake8 with configuration
          flake8 . --count --statistics