name: Ruff Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: false
          
      - name: Install dependencies
        run: uv sync --dev
          
      - name: Lint with ruff
        run: |
          uv run ruff check .
          
      - name: Format check with ruff
        run: |
          uv run ruff format --check .