name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fix SciPy compatibility
        run: |
          python -c "
          import scipy
          try:
              from scipy.signal.windows import hann
              scipy.hanning = hann
              print('Fixed: Added scipy.hanning from windows.hann')
          except (ImportError, AttributeError):
              try:
                  from scipy.signal import hann
                  scipy.hanning = hann
                  print('Fixed: Added scipy.hanning from signal.hann')
              except (ImportError, AttributeError):
                  try:
                      from scipy.signal import hanning
                      scipy.hanning = hanning
                      print('Fixed: Used existing hanning')
                  except (ImportError, AttributeError):
                      print('WARNING: Could not fix scipy.hanning')
          "

      - name: Run tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings